### ISSUE TITLE
Exception gives AttributeError when request fails

### ISSUE THREAD

**Issue by Matthijz98** [sergioteula/python-aliexpress-api#1]
Hi love the package but there is one error that happens once in a while. To be clear i make over 800.000 requests a day and it happens 10 times. Error is reased if the api request times out. You try to catch that error but that does not work correctly

The error:
``
AttributeError 'timeout' object has no attribute 'message'
``
aliexpress_api/helpers/requests.py in api_request at line 10:
```python
def api_request(request, response_name):
    try:
        response = request.getResponse()
    except Exception as e:
        raise ApiRequestException(e.message) # this is where the error happens if the request does not return at all there is no message on the request
```

**Comment by Matthijz98** [comment]
This could be a simple fix:
```python
def api_request(request, response_name):
    try:
        response = request.getResponse()
   except requests.exceptions.Timeout:
        raise ApiRequestException('request timed out')
    except Exception as e:
        raise ApiRequestException(e.message)
```

**Comment by sergioteula** [comment]
Have you tested that fix? Since I can't reproduce the error I'm not able to check what is the exception raised by the timeout. I you confirm that it's tested, I'll go ahead. Thanks!

**Comment by sergioteula** [comment]
Already updated with better exception handling to avoid this error. https://github.com/sergioteula/python-aliexpress-api/releases/tag/v2.1.1
