### ISSUE TITLE
ApiRequestException Error

### ISSUE THREAD

**Issue by arpitgoyall** [sergioteula/python-aliexpress-api#16]
Aliexpress is banned to open in India, How can I change the IP address to solve that request error?

raise ApiRequestException(error) from error
aliexpress_api.errors.exceptions.ApiRequestException: [WinError 10060] A connection attempt failed because the 
connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by sergioteula** [comment]
You should use a VPN or proxy, but that's not something configurable in this module. You should use other tools to achieve that.
