### ISSUE TITLE
UNABLE TO GET THE PRICES FOR VARIOUS COUNTRIES

### ISSUE THREAD

**Issue by tedndege** [sergioteula/python-aliexpress-api#18]
Like the title says im unable to get the prices for a product if i specify country in the get product info request how can i resolve this? ERROR raised is  rProductsNotFoudException('No products found with current parameters') aliexpress_api.errors.exceptions.ProductsNotFoudException: No products found with current parameters

**Comment by sergioteula** [comment]
Maybe that products are not available for that country? If they are not affiliated for an specific country, they won't be available in the API.

**Comment by tedndege** [comment]
i checked the website and the products are available for the country i tried using the official java sdk and the same problem so i think its seems to be an issue with aliexpress api or the feature is deprecated,anyway il just close the issue for now
