### ISSUE TITLE
No products found with current parameters

### ISSUE THREAD

**Issue by gramilla** [sergioteula/python-aliexpress-api#2]
I have encountered a strange error. 

When I get data from some products I get the following error
` File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aliexpress_api/api.py", line 89, in get_products_details
    raise ProductsNotFoudException('No products found with current parameters')
aliexpress_api.errors.exceptions.ProductsNotFoudException: No products found with current parameters`

The link where I get this error 
https://www.aliexpress.com/item/1005003734106859.html
But this link is fine 
https://www.aliexpress.com/item/1005002385229295.html

ID ='https://www.aliexpress.com/item/1005003734106859.html'
def aliapi(aliurl):
    aliinfo = aliexpress.get_products_details(aliurl)
    return(aliinfo)
print(aliapi(ID))

**Comment by gramilla** [comment]
I think I found a pattern. 
Those products with a 0% commission get this error when parsing.

**Comment by sergioteula** [comment]
Yes, products not affiliated by AliExpress are not available through the API. There's nothing we can do.
